import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { resolve } from 'node:path';
import { loadPublicKey } from '../crypto.js';
import { deepMerge } from '../deep_merge.js';

export function loadJson(path: string): Record<string, unknown> {
  if (!existsSync(path)) {
    return {};
  }
  return JSON.parse(readFileSync(path, 'utf-8'));
}

export function sortKeys(obj: unknown): unknown {
  if (obj === null || typeof obj !== 'object') {
    return obj;
  }
  if (Array.isArray(obj)) {
    return obj.map(sortKeys);
  }
  const sorted: Record<string, unknown> = {};
  for (const key of Object.keys(obj).sort()) {
    sorted[key] = sortKeys((obj as Record<string, unknown>)[key]);
  }
  return sorted;
}

export function generateConfigFileContent(
  config: Record<string, unknown>,
  importSource: string
): string {
  const json = JSON.stringify(sortKeys(config), null, 2);

  return `// Auto-generated by lockbox — do not edit
// Modify the relevant clear.json/secret.json files and run \`lockbox generate\`
// Do not import directly — use your config loader

import { deepFreeze } from '${importSource}';

export default deepFreeze(${json} as const);
`;
}

export function loadDefaults(configDir: string): Record<string, unknown> {
  return loadJson(resolve(configDir, 'default.json'));
}

export function loadEnvConfig(
  configDir: string,
  env: string
): {
  clear: Record<string, unknown>;
  secret: Record<string, unknown>;
  secretPath: string;
  generatedPath: string;
} {
  const envDir = resolve(configDir, env);
  const secretPath = resolve(envDir, 'secret.json');
  return {
    clear: loadJson(resolve(envDir, 'clear.json')),
    secret: loadJson(secretPath),
    secretPath,
    generatedPath: resolve(envDir, 'generated.ts'),
  };
}

export function mergeConfigs(
  defaults: Record<string, unknown>,
  envClear: Record<string, unknown>,
  envSecret: Record<string, unknown>
): Record<string, unknown> {
  return deepMerge(defaults, envClear, envSecret);
}

/**
 * Discover environments by scanning subdirectories that contain
 * at least one of clear.json or secret.json.
 */
export function discoverEnvironments(configDir: string): string[] {
  if (!existsSync(configDir)) {
    return [];
  }

  const entries = readdirSync(configDir);
  const envs: string[] = [];

  for (const entry of entries) {
    const entryPath = resolve(configDir, entry);
    if (!statSync(entryPath).isDirectory()) continue;

    const hasClear = existsSync(resolve(entryPath, 'clear.json'));
    const hasSecret = existsSync(resolve(entryPath, 'secret.json'));

    if (hasClear || hasSecret) {
      envs.push(entry);
    }
  }

  return envs.sort();
}

export function loadPublicKeyFromFile(configDir: string): Buffer {
  const pubKeyPath = resolve(configDir, 'lockbox.pub');
  if (!existsSync(pubKeyPath)) {
    throw new Error(`Public key not found at ${pubKeyPath}. Run \`lockbox init\` first.`);
  }

  return loadPublicKey(readFileSync(pubKeyPath, 'utf-8').trim());
}
