import { ENC_PREFIX } from './crypto.js';

const REQUIRED_SENTINEL = '**REQUIRED**';

interface TypeNode {
  kind: 'object' | 'union';
  // For 'object' kind: keys are property names, values are child TypeNodes
  properties?: Map<string, { node: TypeNode; optional: boolean }>;
  // For 'union' kind: the set of literal type strings (e.g. "'mem'" | "'pg'" | "number")
  types?: Set<string>;
}

/**
 * Generate a TypeScript type definition from merged config objects across
 * all environments. Infers union types from distinct values.
 */
export function generateSchemaFileContent(
  mergedConfigs: Record<string, Record<string, unknown>>
): string {
  const envNames = Object.keys(mergedConfigs);
  const envConfigs = Object.values(mergedConfigs);

  if (envConfigs.length === 0) {
    return formatOutput('Record<string, unknown>');
  }

  const tree = buildTypeTree(envNames, envConfigs);
  const typeStr = renderTypeNode(tree, 0);
  return formatOutput(typeStr);
}

function formatOutput(typeBody: string): string {
  return `// Auto-generated by lockbox — do not edit
// Run \`lockbox generate\` to regenerate

export type Config = ${typeBody};
`;
}

function buildTypeTree(
  envNames: string[],
  envConfigs: Record<string, unknown>[]
): TypeNode {
  // Collect all keys across all envs
  const allKeys = new Set<string>();
  for (const cfg of envConfigs) {
    if (cfg && typeof cfg === 'object' && !Array.isArray(cfg)) {
      for (const key of Object.keys(cfg)) {
        allKeys.add(key);
      }
    }
  }

  const properties = new Map<string, { node: TypeNode; optional: boolean }>();

  for (const key of [...allKeys].sort()) {
    const values: unknown[] = [];
    let presentCount = 0;

    for (const cfg of envConfigs) {
      if (cfg && typeof cfg === 'object' && !Array.isArray(cfg) && key in cfg) {
        values.push((cfg as Record<string, unknown>)[key]);
        presentCount++;
      }
    }

    const optional = presentCount < envConfigs.length;
    const node = inferType(envNames, envConfigs, key, values);
    properties.set(key, { node, optional });
  }

  return { kind: 'object', properties };
}

function inferType(
  envNames: string[],
  envConfigs: Record<string, unknown>[],
  key: string,
  values: unknown[]
): TypeNode {
  // If all values are plain objects, recurse
  const allObjects = values.length > 0 && values.every(
    (v) => v !== null && typeof v === 'object' && !Array.isArray(v)
  );

  if (allObjects) {
    // Build sub-configs for recursion: only envs that have this key
    const subConfigs: Record<string, unknown>[] = [];
    const subEnvNames: string[] = [];
    for (let i = 0; i < envConfigs.length; i++) {
      const cfg = envConfigs[i];
      if (cfg && typeof cfg === 'object' && !Array.isArray(cfg) && key in cfg) {
        subConfigs.push((cfg as Record<string, unknown>)[key] as Record<string, unknown>);
        subEnvNames.push(envNames[i]);
      }
    }
    return buildTypeTree(subEnvNames, subConfigs);
  }

  // Leaf: collect distinct type literals
  const types = new Set<string>();

  for (const value of values) {
    if (typeof value === 'string') {
      if (value.startsWith(ENC_PREFIX) || value === REQUIRED_SENTINEL) {
        types.add('string');
      } else {
        types.add(`'${escapeQuotes(value)}'`);
      }
    } else if (typeof value === 'number') {
      types.add(String(value));
    } else if (typeof value === 'boolean') {
      types.add(String(value));
    } else if (value === null) {
      types.add('null');
    } else if (Array.isArray(value)) {
      const elementTypes = inferArrayElementTypes(value);
      if (elementTypes.size === 0) {
        types.add('unknown[]');
      } else {
        const inner = [...elementTypes].sort().join(' | ');
        types.add(elementTypes.size > 1 ? `(${inner})[]` : `${inner}[]`);
      }
    } else {
      types.add('unknown');
    }
  }

  if (types.size === 0) {
    types.add('unknown');
  }

  return { kind: 'union', types: simplifyUnion(types) };
}

function inferArrayElementTypes(arr: unknown[]): Set<string> {
  const types = new Set<string>();
  for (const item of arr) {
    if (typeof item === 'string') {
      if (item.startsWith(ENC_PREFIX) || item === REQUIRED_SENTINEL) {
        types.add('string');
      } else {
        types.add(`'${escapeQuotes(item)}'`);
      }
    } else if (typeof item === 'number') {
      types.add(String(item));
    } else if (typeof item === 'boolean') {
      types.add(String(item));
    } else if (item === null) {
      types.add('null');
    } else if (typeof item === 'object') {
      types.add('Record<string, unknown>');
    }
  }
  return types;
}

function renderTypeNode(node: TypeNode, indent: number): string {
  if (node.kind === 'union') {
    const types = [...node.types!].sort();
    return types.join(' | ');
  }

  const pad = '  '.repeat(indent);
  const innerPad = '  '.repeat(indent + 1);
  const entries: string[] = [];

  for (const [key, { node: child, optional }] of node.properties!) {
    const opt = optional ? '?' : '';
    const safeKey = isValidIdentifier(key) ? key : `'${escapeQuotes(key)}'`;
    const typeStr = renderTypeNode(child, indent + 1);
    entries.push(`${innerPad}${safeKey}${opt}: ${typeStr};`);
  }

  if (entries.length === 0) {
    return 'Record<string, never>';
  }

  return `{\n${entries.join('\n')}\n${pad}}`;
}

/**
 * If `string` is in the union, remove all string literals.
 * Same for `number` with number literals and `boolean` with true/false.
 */
function simplifyUnion(types: Set<string>): Set<string> {
  if (types.has('string')) {
    for (const t of types) {
      if (t.startsWith("'") && t.endsWith("'")) {
        types.delete(t);
      }
    }
  }
  if (types.has('number')) {
    for (const t of types) {
      if (t !== 'number' && /^-?\d+(\.\d+)?$/.test(t)) {
        types.delete(t);
      }
    }
  }
  if (types.has('true') && types.has('false')) {
    types.delete('true');
    types.delete('false');
    types.add('boolean');
  }
  return types;
}

function isValidIdentifier(key: string): boolean {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key);
}

function escapeQuotes(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
